# Generated by Django 5.1.4 on 2025-01-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
