# Generated by Django 5.1.4 on 2025-01-06 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_client_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
            ],
        ),
    ]
