# Generated by Django 5.1.4 on 2025-01-06 23:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_branchoffice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='start',
            new_name='star',
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
